language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-31.0.0
  - android-31
  - extra-android-m2repository

jdk:
- openjdk11

script:
- ./gradlew build generatePomFileForAndroidPermissionsPublication

before_deploy: sed -i "s/{{VERSION_NUMBER}}/${MAJOR_VERSION}\.${MINOR_VERSION}\.${TRAVIS_BUILD_NUMBER}/g" bintray-descriptor-template.json
deploy:
  provider: bintray
  file: "bintray-descriptor-template.json"
  on:
    branch: master
  user: ${TRAVIS_USER}
  key: ${TRAVIS_KEY}
  skip_cleanup: true
